development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool:
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool:
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool:
  username:
  password:
